# Generated by Django 4.1.2 on 2022-10-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fureverhomes_users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_declawed',
            field=models.BooleanField(default=False),
        ),
    ]
