# Generated by Django 4.1.2 on 2022-10-21 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fureverhomes_users_app', '0002_cat_is_declawed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futureowner',
            name='other_preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_address',
        ),
        migrations.AddField(
            model_name='futureowner',
            name='fixed_pref',
            field=models.IntegerField(choices=[(0, 'Must be spayed/neutered'), (1, "Doesn't need to be spayed/neutered")], default=0),
        ),
        migrations.AddField(
            model_name='futureowner',
            name='kids_pref',
            field=models.IntegerField(choices=[(0, 'Must be good with kids'), (1, "Doesn't need to be good with kids")], default=0),
        ),
        migrations.AddField(
            model_name='futureowner',
            name='size_pref',
            field=models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'No Preference')], default=4),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='size',
            field=models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='user_zip',
            field=models.CharField(default=10000, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='futureowner',
            name='age_pref',
            field=models.IntegerField(choices=[(0, 'Young'), (1, 'Adult'), (2, 'Senior')], default=0),
        ),
        migrations.AlterField(
            model_name='futureowner',
            name='sex_pref',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'No Preference')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='futureowner',
            name='type_pref',
            field=models.TextField(choices=[('dog', 'Dog'), ('cat', 'Cat')], default='dog', max_length=5),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='age',
            field=models.IntegerField(blank=True, choices=[(0, 'Young: 0-1 Years'), (1, 'Adult: 1-6 Years'), (2, 'Senior: 6+ Years')], default=0),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unsure')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_dob',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(default='youremail@example.com', max_length=30, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='YourName', max_length=50),
        ),
    ]
