
# Generated by Django 4.1.2 on 2022-11-06 16:18
# Generated by Django 4.1.2 on 2022-11-07 17:20
#>>>>>>> aefd1ecf814553a946bbaf1b227a7f265e3d875b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fureverhomes_users_app', '0004_petprofile_date_uploaded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petprofile',
            options={'ordering': ['date_uploaded']},
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='age',
            field=models.IntegerField(choices=[(0, 'Young: 0-1 Years'), (1, 'Adult: 1-6 Years'), (2, 'Senior: 6+ Years')], default=0),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='pet_profile_photos'),
        ),
    ]
