# Generated by Django 4.1.3 on 2023-01-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fureverhomes_users_app', '0005_alter_petprofile_options_alter_petprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_cause',
            field=models.IntegerField(choices=[(1, 'Threatening Language'), (2, 'Demand of Payment'), (3, 'Surrender of puppies under 8/kittens under 10 weeks'), (4, 'Other')]),
        ),
    ]
