# Generated by Django 4.1.3 on 2023-02-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fureverhomes_users_app', '0006_alter_report_report_cause'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
