# Generated by Django 4.1.3 on 2023-02-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fureverhomes_users_app', '0007_rename_receiver_id_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
