# Generated by Django 4.1.3 on 2023-02-08 00:05

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('fureverhomes_users_app', '0008_message_message_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=1000)),
        ),
    ]
