# Generated by Django 4.1.3 on 2023-02-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        'fureverhomes_users_app',
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.CharField(max_length=1000),
        ),
    ]
