# Generated by Django 4.1.3 on 2023-02-21 18:52

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fureverhomes_users_app', '0011_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=1000)),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_dt',
            field=models.DateTimeField(),
        ),
    ]
