# Generated by Django 4.1.3 on 2023-02-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fureverhomes_users_app', '0012_alter_message_message_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.CharField(max_length=1000),
        ),
    ]
